django_project/django_project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sustav.urls')),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),

]

django_project/sustav/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="Sustav-Početna"),
    path('students/', views.students, name="Sustav-Students"),
    path('courses/', views.courses, name="Sustav-Courses"),
    path('predmet/<predmet>/', views.predmet, name="predmet"),
    path('predmetEdit/<predmet>/', views.predmetEdit, name="predmetEdit"),
    path('studentEdit/<korisnik>/', views.studentEdit, name="studentEdit"),
    path('upisniList/<korisnik>/', views.upisniList, name="upisniList"),
    path('add/<int:pk>/<int:cpk>/', views.add, name="add"),
    path('remove/<int:pk>/<int:cpk>/', views.remove, name="remove"),
    path('passed/<int:pk>/<int:cpk>/', views.passed, name="passed"),
]

django_project/sustav/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from django.contrib.auth.models import AbstractUser

class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=150)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.PositiveSmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class Korisnici(AbstractUser):
    ROLE_CHOICES = (
        ('None', 'None'),
        ('Mentor', 'Mentor'),
        ('Student', 'Student'),
    )
    STATUS_CHOICES = (
        ('Redovni', 'Redovni'),
        ('Izvanredni', 'Izvanredni'),
    )
    role = models.CharField(max_length=7, choices = ROLE_CHOICES)
    status = models.CharField(max_length=10, choices = STATUS_CHOICES, blank=True)

    def __str__(self):
        return self.email
    class Meta:
        
        db_table = 'korisnici'


class Predmeti(models.Model):
    ime = models.CharField(max_length=255)
    kod = models.CharField(max_length=16)
    program = models.TextField()
    bodovi = models.IntegerField()
    sem_redovni = models.IntegerField()
    sem_izvanredni = models.IntegerField()
    izborni = models.CharField(max_length=2)

    def __str__(self):
        return self.ime
    class Meta:
        
        db_table = 'predmeti'


class Upisi(models.Model):
    student = models.ForeignKey('Korisnici', models.DO_NOTHING)
    predmet = models.ForeignKey('Predmeti', models.DO_NOTHING)
    status = models.CharField(max_length=64)

    def __str__(self):
        return (self.student.email+" "+self.predmet.ime+" ("+self.status+")")
    class Meta:
        
        db_table = 'upisi'

django_project/sustav/forms.py
from django import forms
from sustav.models import Predmeti, Korisnici, Upisi
from django.contrib.auth.forms import UserCreationForm

class PredmetForm(forms.ModelForm):
    ime = forms.CharField()
    kod = forms.CharField()
    program = forms.CharField()
    bodovi = forms.IntegerField()
    sem_redovni = forms.IntegerField()
    sem_izvanredni = forms.IntegerField()
    izborni = forms.ChoiceField(choices=(('da', ("da")),('ne', ("ne"))), widget=forms.Select())
    
    class Meta:
        model= Predmeti
        fields=["ime", "kod", "program", "bodovi", "sem_redovni", "sem_izvanredni", "izborni"]

django_project/sustav/views.py
from django.shortcuts import render, redirect
from .models import Korisnici, Predmeti, Upisi
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import *
# Create your views here.

@login_required
def home(request):
    context = {
        'title': "Home",
        'content': Korisnici.objects.all(),

    }
    return render(request, 'sustav/home.html', context)
@login_required
def predmet(request, predmet):
    context = {
        'predmet': Predmeti.objects.filter(ime=predmet).first()
    }
    return render(request, 'sustav/predmet.html', context)
@login_required
def predmetEdit(request, predmet):

    predmet = Predmeti.objects.filter(ime=predmet).first()
    data={"ime": predmet.ime, "kod": predmet.kod, "program": predmet.program, "bodovi": predmet.bodovi, "sem_redovni": predmet.sem_redovni, "sem_izvanredni": predmet.sem_izvanredni, "izborni": predmet.izborni}


    if request.method == 'POST':
        
        form = PredmetForm(request.POST, instance=predmet)
        if form.is_valid():    
            form.save()
            messages.success(request, f'Predmet uspješno promijenjen!')
            return redirect('Sustav-Courses')
    else:
        form = PredmetForm(initial=data)
    context = {
        'form': form,
        'predmet': predmet
    }
    return render(request, 'sustav/predmetEdit.html', context)
@login_required
def studentEdit(request, korisnik):
    content ={
        'upisi' : Upisi.objects.all(),
        'korisnik' : Korisnici.objects.filter(email=korisnik).first(),
        'content' : Predmeti.objects.all()
    }
    korisnik = Korisnici.objects.filter(email=korisnik).first()
    return render(request, 'sustav/studentEdit.html', content)

@login_required
def upisniList(request, korisnik):
    content ={
        'upisi' : Upisi.objects.all(),
        'korisnik' : Korisnici.objects.filter(email=korisnik).first(),
        'content' : Predmeti.objects.all()
    }
    korisnik = Korisnici.objects.filter(email=korisnik).first()
    return render(request, 'sustav/upisniList.html', content)

def add(request, pk, cpk):
    content ={
        'upisi' : Upisi.objects.all(),
        'korisnik' : Korisnici.objects.filter(id=pk).first(),
        'content' : Predmeti.objects.all()
    }
    student = Korisnici.objects.get(id=pk)
    predmet = Predmeti.objects.get(id=cpk)
    email=student.email
    upis = Upisi(student=student, predmet=predmet, status='enrolled')
    try:
        upis.save()
    except:
        return render(request, 'sustav/studentEdit.html', content)

    return render(request, 'sustav/studentEdit.html', content)

def remove(request, pk, cpk):
    content ={
        'upisi' : Upisi.objects.all(),
        'korisnik' : Korisnici.objects.filter(id=pk).first(),
        'content' : Predmeti.objects.all()
    }
    student = Korisnici.objects.get(id=pk)
    predmet = Predmeti.objects.get(id=cpk)
    email=student.email
    try:
        Upisi.objects.filter(student=student, predmet=predmet).delete()
    except:
        return render(request, 'sustav/studentEdit.html', content)

    return render(request, 'sustav/studentEdit.html', content)

def passed(request, pk, cpk):
    content ={
        'upisi' : Upisi.objects.all(),
        'korisnik' : Korisnici.objects.filter(id=pk).first(),
        'content' : Predmeti.objects.all()
    }
    student = Korisnici.objects.get(id=pk)
    predmet = Predmeti.objects.get(id=cpk)
    email=student.email
    upis = Upisi.objects.get(student=student, predmet=predmet)
    upis.status='passed'
    try:
        upis.save()
    except:
        return render(request, 'sustav/studentEdit.html', content)

    return render(request, 'sustav/studentEdit.html', content)



@login_required
def students(request):
    content = {
        'title': "Studenti",
        'content': Korisnici.objects.all()
    }
    return render(request, 'sustav/students.html', content)

@login_required
def courses(request):
    content = {
        'title': "Predmeti",
        'content': Predmeti.objects.all()
    }
    return render(request, 'sustav/courses.html', content)

django_project/sustav/templates/sustav/about.html
{% extends "sustav/base.html" %}
{% block content %}
    <h3>Content test</h3>
{% endblock content %}

django_project/sustav/templates/sustav/courses.html
{% extends "sustav/base.html" %}
{% block content %}
    <h1>Lista predmeta:</h1>
    {% for predmet in content %}
        {{ predmet.ime }} ({{ predmet.kod }}) &nbsp; <a class="btn btn-outline-secondary" href="/predmet/{{ predmet }}">Details</a> &nbsp; <a class="btn btn-outline-secondary" href="/predmetEdit/{{ predmet }}">Edit</a>   <br>
    {% endfor %}
{% endblock content %}

django_project/sustav/templates/sustav/home.html
{% extends "sustav/base.html" %}
{% block content %}
    <h3>Home Page</h3>
    {% for korisnik in content %}
        <h3>{{ korisnik.email }}</h3>
        {{ korisnik.role }}
        {% if korisnik.status != 'none' %}
            {{ korisnik.status }}
        {% endif %}
    {% endfor %}
{% endblock content %}

django_project/sustav/templates/sustav/predmetEdit.html
{% extends "sustav/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <form method='POST'>
        {% csrf_token %}
        {{ form|crispy }}
        
        <button type='submit'>Edit</button><br><br>
        <a href="{% url 'Sustav-Courses' %}">Natrag</a>
    </form>
{% endblock content %}

django_project/sustav/templates/sustav/studentEdit.html
{% extends "sustav/base.html" %}
{% block content %}
    <h2>Lista predmeta:</h2>
    {% for predmet in content %}
        {{ predmet.ime }}  <a class="btn btn-outline-secondary" href="{% url 'add' pk=korisnik.id cpk=predmet.id %}">Add</a><br>
    {% endfor %}
    
{% endblock content %}

{% block content2 %}
    <h2>Upisi ({{ korisnik.email }})</h2>
    
            {% if korisnik.status == 'Redovni' %}
            <h4>1. Semestar:</h4>
            {% for upis in korisnik.upisi_set.all %}
                {% for p in content %}
                    {% if p.id == upis.predmet_id and p.sem_redovni == 1 %}
                        {{ p.ime }} ({{ upis.status }}) <a class="btn btn-outline-secondary" href="{% url 'remove' pk=korisnik.id cpk=upis.predmet_id %}">Remove</a>
                        {% if upis.status == 'enrolled' %}
                            <a class="btn btn-outline-secondary" href="{% url 'passed' pk=korisnik.id cpk=upis.predmet_id %}">Passed</a>
                        {% endif %}
                        <br>
                    {% endif %}
                {% endfor %}
            {% endfor %}
            <br>
            <h4>2. Semestar:</h4>
            {% for upis in korisnik.upisi_set.all %}
                {% for p in content %}
                    {% if p.id == upis.predmet_id and p.sem_redovni == 2 %}
                        {{ p.ime }} ({{ upis.status }}) <a class="btn btn-outline-secondary" href="{% url 'remove' pk=korisnik.id cpk=upis.predmet_id %}">Remove</a>
                        {% if upis.status == 'enrolled' %}
                            <a class="btn btn-outline-secondary" href="{% url 'passed' pk=korisnik.id cpk=upis.predmet_id %}">Passed</a>
                        {% endif %}<br>
                    {% endif %}
                {% endfor %}
            {% endfor %}
            <br>
            <h4>3. Semestar:</h4>
            {% for upis in korisnik.upisi_set.all %}
                {% for p in content %}
                    {% if p.id == upis.predmet_id and p.sem_redovni == 3 %}
                        {{ p.ime }} ({{ upis.status }}) <a class="btn btn-outline-secondary" href="{% url 'remove' pk=korisnik.id cpk=upis.predmet_id %}">Remove</a>
                        {% if upis.status == 'enrolled' %}
                            <a class="btn btn-outline-secondary" href="{% url 'passed' pk=korisnik.id cpk=upis.predmet_id %}">Passed</a>
                        {% endif %}<br>
                    {% endif %}
                {% endfor %}
            {% endfor %}
            <br>
            <h4>4. Semestar:</h4>
            {% for upis in korisnik.upisi_set.all %}
                {% for p in content %}
                    {% if p.id == upis.predmet_id and p.sem_redovni == 4 %}
                        {{ p.ime }} ({{ upis.status }}) <a class="btn btn-outline-secondary" href="{% url 'remove' pk=korisnik.id cpk=upis.predmet_id %}">Remove</a>
                        {% if upis.status == 'enrolled' %}
                            <a class="btn btn-outline-secondary" href="{% url 'passed' pk=korisnik.id cpk=upis.predmet_id %}">Passed</a>
                        {% endif %}<br>
                    {% endif %}
                {% endfor %}
            {% endfor %}
            <br>
            <h4>5. Semestar:</h4>
            {% for upis in korisnik.upisi_set.all %}
                {% for p in content %}
                    {% if p.id == upis.predmet_id and p.sem_redovni == 5 %}
                        {{ p.ime }} ({{ upis.status }}) <a class="btn btn-outline-secondary" href="{% url 'remove' pk=korisnik.id cpk=upis.predmet_id %}">Remove</a>
                        {% if upis.status == 'enrolled' %}
                            <a class="btn btn-outline-secondary" href="{% url 'passed' pk=korisnik.id cpk=upis.predmet_id %}">Passed</a>
                        {% endif %}<br>
                    {% endif %}
                {% endfor %}
            {% endfor %}
            <br>
            <h4>6. Semestar:</h4>
            {% for upis in korisnik.upisi_set.all %}
                {% for p in content %}
                    {% if p.id == upis.predmet_id and p.sem_redovni == 6 %}
                        {{ p.ime }} ({{ upis.status }}) <a class="btn btn-outline-secondary" href="{% url 'remove' pk=korisnik.id cpk=upis.predmet_id %}">Remove</a>
                        {% if upis.status == 'enrolled' %}
                            <a class="btn btn-outline-secondary" href="{% url 'passed' pk=korisnik.id cpk=upis.predmet_id %}">Passed</a>
                        {% endif %}<br>
                    {% endif %}
                {% endfor %}
            {% endfor %}
            <br>
            
            {% elif korisnik.status == 'Izvanredni' %}
            <h4>1. Semestar:</h4>
            {% for upis in korisnik.upisi_set.all %}
                {% for p in content %}
                    {% if p.id == upis.predmet_id and p.sem_izvanredni == 1 %}
                        {{ p.ime }} ({{ upis.status }}) <a class="btn btn-outline-secondary" href="{% url 'remove' pk=korisnik.id cpk=upis.predmet_id %}">Remove</a>
                        {% if upis.status == 'enrolled' %}
                            <a class="btn btn-outline-secondary" href="{% url 'passed' pk=korisnik.id cpk=upis.predmet_id %}">Passed</a>
                        {% endif %}<br>
                    {% endif %}
                {% endfor %}
            {% endfor %}
            <br>
            <h4>2. Semestar:</h4>
            {% for upis in korisnik.upisi_set.all %}
                {% for p in content %}
                    {% if p.id == upis.predmet_id and p.sem_izvanredni == 2 %}
                        {{ p.ime }} ({{ upis.status }}) <a class="btn btn-outline-secondary" href="{% url 'remove' pk=korisnik.id cpk=upis.predmet_id %}">Remove</a>
                        {% if upis.status == 'enrolled' %}
                            <a class="btn btn-outline-secondary" href="{% url 'passed' pk=korisnik.id cpk=upis.predmet_id %}">Passed</a>
                        {% endif %}<br>
                    {% endif %}
                {% endfor %}
            {% endfor %}
            <br>
            <h4>3. Semestar:</h4>
            {% for upis in korisnik.upisi_set.all %}
                {% for p in content %}
                    {% if p.id == upis.predmet_id and p.sem_izvanredni == 3 %}
                        {{ p.ime }} ({{ upis.status }}) <a class="btn btn-outline-secondary" href="{% url 'remove' pk=korisnik.id cpk=upis.predmet_id %}">Remove</a>
                        {% if upis.status == 'enrolled' %}
                            <a class="btn btn-outline-secondary" href="{% url 'passed' pk=korisnik.id cpk=upis.predmet_id %}">Passed</a>
                        {% endif %}<br>
                    {% endif %}
                {% endfor %}
            {% endfor %}
            <br>
            <h4>4. Semestar:</h4>
            {% for upis in korisnik.upisi_set.all %}
                {% for p in content %}
                    {% if p.id == upis.predmet_id and p.sem_izvanredni == 4 %}
                        {{ p.ime }} ({{ upis.status }}) <a class="btn btn-outline-secondary" href="{% url 'remove' pk=korisnik.id cpk=upis.predmet_id %}">Remove</a>
                        {% if upis.status == 'enrolled' %}
                            <a class="btn btn-outline-secondary" href="{% url 'passed' pk=korisnik.id cpk=upis.predmet_id %}">Passed</a>
                        {% endif %}<br>
                    {% endif %}
                {% endfor %}
            {% endfor %}
            <br>
            <h4>5. Semestar:</h4>
            {% for upis in korisnik.upisi_set.all %}
                {% for p in content %}
                    {% if p.id == upis.predmet_id and p.sem_izvanredni == 5 %}
                        {{ p.ime }} ({{ upis.status }}) <a class="btn btn-outline-secondary" href="{% url 'remove' pk=korisnik.id cpk=upis.predmet_id %}">Remove</a>
                        {% if upis.status == 'enrolled' %}
                            <a class="btn btn-outline-secondary" href="{% url 'passed' pk=korisnik.id cpk=upis.predmet_id %}">Passed</a>
                        {% endif %}<br>
                    {% endif %}
                {% endfor %}
            {% endfor %}
            <br>
            <h4>6. Semestar:</h4>
            {% for upis in korisnik.upisi_set.all %}
                {% for p in content %}
                    {% if p.id == upis.predmet_id and p.sem_izvanredni == 6 %}
                        {{ p.ime }} ({{ upis.status }}) <a class="btn btn-outline-secondary" href="{% url 'remove' pk=korisnik.id cpk=upis.predmet_id %}">Remove</a>
                        {% if upis.status == 'enrolled' %}
                            <a class="btn btn-outline-secondary" href="{% url 'passed' pk=korisnik.id cpk=upis.predmet_id %}">Passed</a>
                        {% endif %}<br>
                    {% endif %}
                {% endfor %}
            {% endfor %}
            <br>
            <h4>7. Semestar:</h4>
            {% for upis in korisnik.upisi_set.all %}
                {% for p in content %}
                    {% if p.id == upis.predmet_id and p.sem_izvanredni == 7 %}
                        {{ p.ime }} ({{ upis.status }}) <a class="btn btn-outline-secondary" href="{% url 'remove' pk=korisnik.id cpk=upis.predmet_id %}">Remove</a>
                        {% if upis.status == 'enrolled' %}
                            <a class="btn btn-outline-secondary" href="{% url 'passed' pk=korisnik.id cpk=upis.predmet_id %}">Passed</a>
                        {% endif %}<br>
                    {% endif %}
                {% endfor %}
            {% endfor %}
            <br>
            <h4>8. Semestar:</h4>
            {% for upis in korisnik.upisi_set.all %}
                {% for p in content %}
                    {% if p.id == upis.predmet_id and p.sem_izvanredni == 8 %}
                        {{ p.ime }} ({{ upis.status }}) <a class="btn btn-outline-secondary" href="{% url 'remove' pk=korisnik.id cpk=upis.predmet_id %}">Remove</a>
                        {% if upis.status == 'enrolled' %}
                            <a class="btn btn-outline-secondary" href="{% url 'passed' pk=korisnik.id cpk=upis.predmet_id %}">Passed</a>
                        {% endif %}<br>
                    {% endif %}
                {% endfor %}
            {% endfor %}
            <br>
            {% endif %}
    
    
    <a href="{% url 'Sustav-Students' %}">Natrag</a>
{% endblock content2%}

django_project/sustav/templates/sustav/upisniList.html
{% extends "sustav/base.html" %}


{% block content %}
    <h2>Upisi ({{ korisnik.email }})</h2>
    
            {% if korisnik.status == 'Redovni' %}
            <h4>1. Semestar:</h4>
            {% for upis in korisnik.upisi_set.all %}
                {% for p in content %}
                    {% if p.id == upis.predmet_id and p.sem_redovni == 1 %}
                        {{ p.ime }} ({{ upis.status }})<br>
                    {% endif %}
                {% endfor %}
            {% endfor %}
            <br>
            <h4>2. Semestar:</h4>
            {% for upis in korisnik.upisi_set.all %}
                {% for p in content %}
                    {% if p.id == upis.predmet_id and p.sem_redovni == 2 %}
                        {{ p.ime }} ({{ upis.status }})<br>
                    {% endif %}
                {% endfor %}
            {% endfor %}
            <br>
            <h4>3. Semestar:</h4>
            {% for upis in korisnik.upisi_set.all %}
                {% for p in content %}
                    {% if p.id == upis.predmet_id and p.sem_redovni == 3 %}
                        {{ p.ime }} ({{ upis.status }})<br>
                    {% endif %}
                {% endfor %}
            {% endfor %}
            <br>
            <h4>4. Semestar:</h4>
            {% for upis in korisnik.upisi_set.all %}
                {% for p in content %}
                    {% if p.id == upis.predmet_id and p.sem_redovni == 4 %}
                        {{ p.ime }} ({{ upis.status }})<br>
                    {% endif %}
                {% endfor %}
            {% endfor %}
            <br>
            <h4>5. Semestar:</h4>
            {% for upis in korisnik.upisi_set.all %}
                {% for p in content %}
                    {% if p.id == upis.predmet_id and p.sem_redovni == 5 %}
                        {{ p.ime }} ({{ upis.status }}) <br>
                    {% endif %}
                {% endfor %}
            {% endfor %}
            <br>
            <h4>6. Semestar:</h4>
            {% for upis in korisnik.upisi_set.all %}
                {% for p in content %}
                    {% if p.id == upis.predmet_id and p.sem_redovni == 6 %}
                        {{ p.ime }} ({{ upis.status }}) <br>
                    {% endif %}
                {% endfor %}
            {% endfor %}
            <br>
            
            {% elif korisnik.status == 'Izvanredni' %}
            <h4>1. Semestar:</h4>
            {% for upis in korisnik.upisi_set.all %}
                {% for p in content %}
                    {% if p.id == upis.predmet_id and p.sem_izvanredni == 1 %}
                        {{ p.ime }} ({{ upis.status }})<br>
                    {% endif %}
                {% endfor %}
            {% endfor %}
            <br>
            <h4>2. Semestar:</h4>
            {% for upis in korisnik.upisi_set.all %}
                {% for p in content %}
                    {% if p.id == upis.predmet_id and p.sem_izvanredni == 2 %}
                        {{ p.ime }} ({{ upis.status }})<br>
                    {% endif %}
                {% endfor %}
            {% endfor %}
            <br>
            <h4>3. Semestar:</h4>
            {% for upis in korisnik.upisi_set.all %}
                {% for p in content %}
                    {% if p.id == upis.predmet_id and p.sem_izvanredni == 3 %}
                        {{ p.ime }} ({{ upis.status }})<br>
                    {% endif %}
                {% endfor %}
            {% endfor %}
            <br>
            <h4>4. Semestar:</h4>
            {% for upis in korisnik.upisi_set.all %}
                {% for p in content %}
                    {% if p.id == upis.predmet_id and p.sem_izvanredni == 4 %}
                        {{ p.ime }} ({{ upis.status }})<br>
                    {% endif %}
                {% endfor %}
            {% endfor %}
            <br>
            <h4>5. Semestar:</h4>
            {% for upis in korisnik.upisi_set.all %}
                {% for p in content %}
                    {% if p.id == upis.predmet_id and p.sem_izvanredni == 5 %}
                        {{ p.ime }} ({{ upis.status }}) <br>
                    {% endif %}
                {% endfor %}
            {% endfor %}
            <br>
            <h4>6. Semestar:</h4>
            {% for upis in korisnik.upisi_set.all %}
                {% for p in content %}
                    {% if p.id == upis.predmet_id and p.sem_izvanredni == 6 %}
                        {{ p.ime }} ({{ upis.status }}) <br>
                    {% endif %}
                {% endfor %}
            {% endfor %}
            <br>
            <h4>7. Semestar:</h4>
            {% for upis in korisnik.upisi_set.all %}
                {% for p in content %}
                    {% if p.id == upis.predmet_id and p.sem_izvanredni == 7 %}
                        {{ p.ime }} ({{ upis.status }}) <br>
                    {% endif %}
                {% endfor %}
            {% endfor %}
            <br>
            <h4>8. Semestar:</h4>
            {% for upis in korisnik.upisi_set.all %}
                {% for p in content %}
                    {% if p.id == upis.predmet_id and p.sem_izvanredni == 8 %}
                        {{ p.ime }} ({{ upis.status }}) <br>
                    {% endif %}
                {% endfor %}
            {% endfor %}
            <br>
            {% endif %}
    
    
    <a href="{% url 'Sustav-Početna' %}">Natrag</a>
{% endblock content%}